package me.rerere.rikkahub.desktop.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal data class PresetTheme(
    val id: String,
    val light: ColorScheme,
    val dark: ColorScheme,
) {
    fun scheme(darkMode: Boolean): ColorScheme = if (darkMode) dark else light
}

internal val presetThemes = listOf(
    PresetTheme(
        id = "sakura",
        light = lightColorScheme(
            primary = Color(0xFF8E4955),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFD9DD),
            onPrimaryContainer = Color(0xFF72333E),
            secondary = Color(0xFF76565A),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFFD9DD),
            onSecondaryContainer = Color(0xFF5C3F43),
            tertiary = Color(0xFF785831),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFDDB8),
            onTertiaryContainer = Color(0xFF5E411C),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF22191A),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF22191A),
            surfaceVariant = Color(0xFFF3DDDF),
            onSurfaceVariant = Color(0xFF524345),
            outline = Color(0xFF847374),
            outlineVariant = Color(0xFFD7C1C3),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF382E2F),
            inverseOnSurface = Color(0xFFFEEDED),
            inversePrimary = Color(0xFFFFB2BC),
            surfaceDim = Color(0xFFE7D6D7),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0F1),
            surfaceContainer = Color(0xFFFBEAEB),
            surfaceContainerHigh = Color(0xFFF6E4E5),
            surfaceContainerHighest = Color(0xFFF0DEDF),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFFFB2BC),
            onPrimary = Color(0xFF561D28),
            primaryContainer = Color(0xFF72333E),
            onPrimaryContainer = Color(0xFFFFD9DD),
            secondary = Color(0xFFE5BDC1),
            onSecondary = Color(0xFF43292D),
            secondaryContainer = Color(0xFF5C3F43),
            onSecondaryContainer = Color(0xFFFFD9DD),
            tertiary = Color(0xFFEABF8F),
            onTertiary = Color(0xFF452B07),
            tertiaryContainer = Color(0xFF5E411C),
            onTertiaryContainer = Color(0xFFFFDDB8),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF1A1112),
            onBackground = Color(0xFFF0DEDF),
            surface = Color(0xFF1A1112),
            onSurface = Color(0xFFF0DEDF),
            surfaceVariant = Color(0xFF524345),
            onSurfaceVariant = Color(0xFFD7C1C3),
            outline = Color(0xFF9F8C8E),
            outlineVariant = Color(0xFF524345),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFF0DEDF),
            inverseOnSurface = Color(0xFF382E2F),
            inversePrimary = Color(0xFF8E4955),
            surfaceDim = Color(0xFF1A1112),
            surfaceBright = Color(0xFF413738),
            surfaceContainerLowest = Color(0xFF140C0D),
            surfaceContainerLow = Color(0xFF22191A),
            surfaceContainer = Color(0xFF261D1E),
            surfaceContainerHigh = Color(0xFF312828),
            surfaceContainerHighest = Color(0xFF3D3233),
        )
    ),
    PresetTheme(
        id = "ocean",
        light = lightColorScheme(
            primary = Color(0xFF116682),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFBDE9FF),
            onPrimaryContainer = Color(0xFF004D64),
            secondary = Color(0xFF4D616C),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD0E6F2),
            onSecondaryContainer = Color(0xFF354A53),
            tertiary = Color(0xFF5D5B7D),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFE3DFFF),
            onTertiaryContainer = Color(0xFF454364),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            background = Color(0xFFF6FAFD),
            onBackground = Color(0xFF171C1F),
            surface = Color(0xFFF6FAFD),
            onSurface = Color(0xFF171C1F),
            surfaceVariant = Color(0xFFDCE4E9),
            onSurfaceVariant = Color(0xFF40484C),
            outline = Color(0xFF70787D),
            outlineVariant = Color(0xFFC0C8CD),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2C3134),
            inverseOnSurface = Color(0xFFEDF1F5),
            inversePrimary = Color(0xFF8BD0EF),
            surfaceDim = Color(0xFFD6DBDE),
            surfaceBright = Color(0xFFF6FAFD),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF0F4F8),
            surfaceContainer = Color(0xFFEAEEF2),
            surfaceContainerHigh = Color(0xFFE4E9EC),
            surfaceContainerHighest = Color(0xFFDFE3E7),
        ),
        dark = darkColorScheme(
            primary = Color(0xFF8BD0EF),
            onPrimary = Color(0xFF003546),
            primaryContainer = Color(0xFF004D64),
            onPrimaryContainer = Color(0xFFBDE9FF),
            secondary = Color(0xFFB4CAD6),
            onSecondary = Color(0xFF1F333C),
            secondaryContainer = Color(0xFF354A53),
            onSecondaryContainer = Color(0xFFD0E6F2),
            tertiary = Color(0xFFC6C2EA),
            onTertiary = Color(0xFF2E2D4D),
            tertiaryContainer = Color(0xFF454364),
            onTertiaryContainer = Color(0xFFE3DFFF),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF0F1417),
            onBackground = Color(0xFFDFE3E7),
            surface = Color(0xFF0F1417),
            onSurface = Color(0xFFDFE3E7),
            surfaceVariant = Color(0xFF40484C),
            onSurfaceVariant = Color(0xFFC0C8CD),
            outline = Color(0xFF8A9297),
            outlineVariant = Color(0xFF40484C),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFDFE3E7),
            inverseOnSurface = Color(0xFF2C3134),
            inversePrimary = Color(0xFF116682),
            surfaceDim = Color(0xFF0F1417),
            surfaceBright = Color(0xFF353A3D),
            surfaceContainerLowest = Color(0xFF0A0F11),
            surfaceContainerLow = Color(0xFF171C1F),
            surfaceContainer = Color(0xFF1B2023),
            surfaceContainerHigh = Color(0xFF262B2D),
            surfaceContainerHighest = Color(0xFF303538),
        )
    ),
    PresetTheme(
        id = "spring",
        light = lightColorScheme(
            primary = Color(0xFF4C662B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFCDEDA3),
            onPrimaryContainer = Color(0xFF354E16),
            secondary = Color(0xFF586249),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFDCE7C8),
            onSecondaryContainer = Color(0xFF404A33),
            tertiary = Color(0xFF386663),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFBCECE7),
            onTertiaryContainer = Color(0xFF1F4E4B),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            background = Color(0xFFF9FAEF),
            onBackground = Color(0xFF1A1C16),
            surface = Color(0xFFF9FAEF),
            onSurface = Color(0xFF1A1C16),
            surfaceVariant = Color(0xFFE1E4D5),
            onSurfaceVariant = Color(0xFF44483D),
            outline = Color(0xFF75796C),
            outlineVariant = Color(0xFFC5C8BA),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2F312A),
            inverseOnSurface = Color(0xFFF1F2E6),
            inversePrimary = Color(0xFFB1D18A),
            surfaceDim = Color(0xFFDADBD0),
            surfaceBright = Color(0xFFF9FAEF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF3F4E9),
            surfaceContainer = Color(0xFFEEEFE3),
            surfaceContainerHigh = Color(0xFFE8E9DE),
            surfaceContainerHighest = Color(0xFFE2E3D8),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFB1D18A),
            onPrimary = Color(0xFF1F3701),
            primaryContainer = Color(0xFF354E16),
            onPrimaryContainer = Color(0xFFCDEDA3),
            secondary = Color(0xFFBFCBAD),
            onSecondary = Color(0xFF2A331E),
            secondaryContainer = Color(0xFF404A33),
            onSecondaryContainer = Color(0xFFDCE7C8),
            tertiary = Color(0xFFA0D0CB),
            onTertiary = Color(0xFF003735),
            tertiaryContainer = Color(0xFF1F4E4B),
            onTertiaryContainer = Color(0xFFBCECE7),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF12140E),
            onBackground = Color(0xFFE2E3D8),
            surface = Color(0xFF12140E),
            onSurface = Color(0xFFE2E3D8),
            surfaceVariant = Color(0xFF44483D),
            onSurfaceVariant = Color(0xFFC5C8BA),
            outline = Color(0xFF8F9285),
            outlineVariant = Color(0xFF44483D),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE2E3D8),
            inverseOnSurface = Color(0xFF2F312A),
            inversePrimary = Color(0xFF4C662B),
            surfaceDim = Color(0xFF12140E),
            surfaceBright = Color(0xFF383A32),
            surfaceContainerLowest = Color(0xFF0C0F09),
            surfaceContainerLow = Color(0xFF1A1C16),
            surfaceContainer = Color(0xFF1E201A),
            surfaceContainerHigh = Color(0xFF282B24),
            surfaceContainerHighest = Color(0xFF33362E),
        )
    ),
    PresetTheme(
        id = "autumn",
        light = lightColorScheme(
            primary = Color(0xFF735C0C),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFFFE08B),
            onPrimaryContainer = Color(0xFF584400),
            secondary = Color(0xFF695D3F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF2E1BB),
            onSecondaryContainer = Color(0xFF50462A),
            tertiary = Color(0xFF47664A),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFC8ECC9),
            onTertiaryContainer = Color(0xFF2F4D34),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF93000A),
            background = Color(0xFFFFF8F1),
            onBackground = Color(0xFF1F1B13),
            surface = Color(0xFFFFF8F1),
            onSurface = Color(0xFF1F1B13),
            surfaceVariant = Color(0xFFEBE1CF),
            onSurfaceVariant = Color(0xFF4C4639),
            outline = Color(0xFF7E7667),
            outlineVariant = Color(0xFFCFC6B4),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF343027),
            inverseOnSurface = Color(0xFFF8F0E2),
            inversePrimary = Color(0xFFE3C46D),
            surfaceDim = Color(0xFFE1D9CC),
            surfaceBright = Color(0xFFFFF8F1),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFBF3E5),
            surfaceContainer = Color(0xFFF5EDDF),
            surfaceContainerHigh = Color(0xFFF0E7D9),
            surfaceContainerHighest = Color(0xFFEAE1D4),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFE3C46D),
            onPrimary = Color(0xFF3D2F00),
            primaryContainer = Color(0xFF584400),
            onPrimaryContainer = Color(0xFFFFE08B),
            secondary = Color(0xFFD5C5A1),
            onSecondary = Color(0xFF392F15),
            secondaryContainer = Color(0xFF50462A),
            onSecondaryContainer = Color(0xFFF2E1BB),
            tertiary = Color(0xFFADCFAE),
            onTertiary = Color(0xFF19361F),
            tertiaryContainer = Color(0xFF2F4D34),
            onTertiaryContainer = Color(0xFFC8ECC9),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF16130B),
            onBackground = Color(0xFFEAE1D4),
            surface = Color(0xFF16130B),
            onSurface = Color(0xFFEAE1D4),
            surfaceVariant = Color(0xFF4C4639),
            onSurfaceVariant = Color(0xFFCFC6B4),
            outline = Color(0xFF989080),
            outlineVariant = Color(0xFF4C4639),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFEAE1D4),
            inverseOnSurface = Color(0xFF343027),
            inversePrimary = Color(0xFF735C0C),
            surfaceDim = Color(0xFF16130B),
            surfaceBright = Color(0xFF3D392F),
            surfaceContainerLowest = Color(0xFF110E07),
            surfaceContainerLow = Color(0xFF1F1B13),
            surfaceContainer = Color(0xFF231F17),
            surfaceContainerHigh = Color(0xFF2D2A21),
            surfaceContainerHighest = Color(0xFF38342B),
        )
    ),
    PresetTheme(
        id = "black",
        light = lightColorScheme(
            primary = Color(0xFF606060),
            onPrimary = Color(0xFFFFFCFC),
            primaryContainer = Color(0xFFE6E6E6),
            onPrimaryContainer = Color(0xFF424242),
            secondary = Color(0xFF424242),
            onSecondary = Color(0xFF6E6E6E),
            secondaryContainer = Color(0xFFF3F3F3),
            onSecondaryContainer = Color(0xFF575757),
            tertiary = Color(0xFF343434),
            onTertiary = Color(0xFFFCFCFC),
            tertiaryContainer = Color(0xFF444444),
            onTertiaryContainer = Color(0xFFB5B5B5),
            error = Color(0xFFDC2626),
            onError = Color(0xFFFCFCFC),
            errorContainer = Color(0xFFFEE2E2),
            onErrorContainer = Color(0xFF991B1B),
            background = Color(0xFFFFFFFF),
            onBackground = Color(0xFF252525),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF252525),
            surfaceVariant = Color(0xFFF7F7F7),
            onSurfaceVariant = Color(0xFF444444),
            outline = Color(0xFFB5B5B5),
            outlineVariant = Color(0xFFEBEBEB),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF343434),
            inverseOnSurface = Color(0xFFEEEEF0),
            inversePrimary = Color(0xFFEBEBEB),
            surfaceDim = Color(0xFFF7F7F7),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF8F8F8),
            surfaceContainer = Color(0xFFF7F7F7),
            surfaceContainerHigh = Color(0xFFEBEBEB),
            surfaceContainerHighest = Color(0xFFE8E8E8),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFEBEBEB),
            onPrimary = Color(0xFF343434),
            primaryContainer = Color(0xFF3B3B3B),
            onPrimaryContainer = Color(0xFFB5B5B5),
            secondary = Color(0xFFB5B5B5),
            onSecondary = Color(0xFF343434),
            secondaryContainer = Color(0xFF444444),
            onSecondaryContainer = Color(0xFFFCFCFC),
            tertiary = Color(0xFFEBEBEB),
            onTertiary = Color(0xFF343434),
            tertiaryContainer = Color(0xFF444444),
            onTertiaryContainer = Color(0xFFB5B5B5),
            error = Color(0xFFEF4444),
            onError = Color(0xFF7F1D1D),
            errorContainer = Color(0xFF991B1B),
            onErrorContainer = Color(0xFFFEE2E2),
            background = Color(0xFF1C1C1C),
            onBackground = Color(0xFFFCFCFC),
            surface = Color(0xFF1C1C1C),
            onSurface = Color(0xFFFCFCFC),
            surfaceVariant = Color(0xFF444444),
            onSurfaceVariant = Color(0xFFB5B5B5),
            outline = Color(0xFF8E8E8E),
            outlineVariant = Color(0xFF444444),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFFCFCFC),
            inverseOnSurface = Color(0xFF343434),
            inversePrimary = Color(0xFF8E8E8E),
            surfaceDim = Color(0xFF252525),
            surfaceBright = Color(0xFF444444),
            surfaceContainerLowest = Color(0xFF1A1A1A),
            surfaceContainerLow = Color(0xFF252525),
            surfaceContainer = Color(0xFF2A2A2A),
            surfaceContainerHigh = Color(0xFF343434),
            surfaceContainerHighest = Color(0xFF3F3F3F),
        )
    ),
)

internal val presetThemeIds = presetThemes.map { it.id }

internal fun findPresetTheme(themeId: String): PresetTheme {
    return presetThemes.find { it.id == themeId } ?: presetThemes.first()
}
