package me.rerere.rikkahub

object DesktopResources {
    val strings: Map<Int, String> = mapOf(
        R.string.about_page_github to "Github",
        R.string.about_page_license to "License",
        R.string.about_page_system to "System",
        R.string.about_page_title to "About",
        R.string.about_page_version to "Version",
        R.string.about_page_website to "Website",
        R.string.add to "Add",
        R.string.app_name to "RikkaHub",
        R.string.assistant_detail_basic_desc to "Configure name, avatar, model, and parameters",
        R.string.assistant_detail_injections_desc to "Configure mode injections and lorebooks",
        R.string.assistant_detail_local_tools_desc to "Enable local tools like JavaScript engine",
        R.string.assistant_detail_mcp_desc to "Configure MCP server tools for the assistant",
        R.string.assistant_detail_memory_desc to "Manage assistant memory and recent chat references",
        R.string.assistant_detail_prompt_desc to "Set system prompts, message templates, and regex rules",
        R.string.assistant_detail_request_desc to "Configure custom request headers and body parameters",
        R.string.assistant_importer_import_failed to "Import failed",
        R.string.assistant_importer_import_tavern_json to "Import Tavern Character Card (JSON)",
        R.string.assistant_importer_import_tavern_png to "Import Tavern Character Card (PNG)",
        R.string.assistant_importer_importing to "Importing...",
        R.string.assistant_importer_missing_data_field to "Missing data field",
        R.string.assistant_importer_missing_name_field to "Missing name field",
        R.string.assistant_importer_missing_spec_field to "Missing spec field",
        R.string.assistant_importer_read_json_failed to "Failed to read JSON",
        R.string.assistant_importer_unsupported_file_type to "Unsupported file type: %s",
        R.string.assistant_importer_unsupported_spec to "Unsupported spec: %s",
        R.string.assistant_page_actions to "Actions",
        R.string.assistant_page_add to "Add",
        R.string.assistant_page_add_body to "Add Body",
        R.string.assistant_page_add_header to "Add Header",
        R.string.assistant_page_available_variables to "\"Available variables: \"",
        R.string.assistant_page_background_set to "Background image set",
        R.string.assistant_page_balanced to "Balanced",
        R.string.assistant_page_body_key to "Body Key",
        R.string.assistant_page_body_value to "Body Value (JSON)",
        R.string.assistant_page_cancel to "Cancel",
        R.string.assistant_page_change_background to "Change Background Image",
        R.string.assistant_page_chaotic to "Chaotic (Dangerous)",
        R.string.assistant_page_chat_background to "Chat Background",
        R.string.assistant_page_chat_background_desc to "Set background image for assistant chat page",
        R.string.assistant_page_chat_model to "Chat Model",
        R.string.assistant_page_chat_model_desc to "Set the default chat model for the assistant. If not set, the global default chat model will be used",
        R.string.assistant_page_clone to "Clone",
        R.string.assistant_page_confirm to "Confirm",
        R.string.assistant_page_context_message_count to "Context Message Size: %d",
        R.string.assistant_page_context_message_desc to "Controls how many historical messages will be sent to the model as context. Messages exceeding this number will be ignored, only the most recent N messages will be retained, which can save tokens",
        R.string.assistant_page_context_message_size to "Context Message Size",
        R.string.assistant_page_context_message_unlimited to "Unlimited context messages",
        R.string.assistant_page_creative to "Creative",
        R.string.assistant_page_current_assistant to "Current Assistant",
        R.string.assistant_page_custom_bodies to "Custom Body",
        R.string.assistant_page_custom_headers to "Custom Headers",
        R.string.assistant_page_default_assistant to "Default Assistant",
        R.string.assistant_page_delete to "Delete",
        R.string.assistant_page_delete_body to "Delete Body",
        R.string.assistant_page_delete_dialog_text to "Are you sure you want to delete this assistant? This action cannot be undone.",
        R.string.assistant_page_delete_header to "Delete Header",
        R.string.assistant_page_enter_image_url to "Enter Image URL",
        R.string.assistant_page_header_name to "Header Name",
        R.string.assistant_page_header_value to "Header Value",
        R.string.assistant_page_image_url to "Image URL",
        R.string.assistant_page_invalid_json to "Invalid JSON: %s",
        R.string.assistant_page_local_tools_javascript_engine_desc to "Execute JavaScript code with QuickJS engine for calculations and scripting",
        R.string.assistant_page_local_tools_javascript_engine_title to "JavaScript Engine",
        R.string.assistant_page_manage_memory_title to "Manage Memory",
        R.string.assistant_page_max_tokens to "Max Tokens",
        R.string.assistant_page_max_tokens_desc to "Maximum number of tokens to generate. Leave empty for no limit.",
        R.string.assistant_page_max_tokens_limit to "Limit: %d tokens",
        R.string.assistant_page_max_tokens_no_limit to "No limit",
        R.string.assistant_page_max_tokens_no_token_limit to "No token limit",
        R.string.assistant_page_memory to "Memory",
        R.string.assistant_page_memory_count to "Memory: %d",
        R.string.assistant_page_memory_desc to "When memory is enabled, the model will try to actively record your information during conversations and use it in subsequent conversations. This feature requires the model to support tool calls to work properly",
        R.string.assistant_page_message_template to "Message Content Template",
        R.string.assistant_page_message_template_desc to "Controls the content format of chat messages before being sent to the LLM, usually no need to modify",
        R.string.assistant_page_name to "Assistant Name",
        R.string.assistant_page_preset_messages to "Preset Chat Messages",
        R.string.assistant_page_preset_messages_desc to "Set initial conversation messages",
        R.string.assistant_page_quick_message_content to "Content",
        R.string.assistant_page_quick_message_title to "Title",
        R.string.assistant_page_quick_messages to "Quick Messages",
        R.string.assistant_page_quick_messages_desc to "Configure quick message shortcuts",
        R.string.assistant_page_recent_chats to "Reference Recent Chats",
        R.string.assistant_page_recent_chats_desc to "When enabled, the assistant will reference recent chat history to provide more contextual responses",
        R.string.assistant_page_regex_affecting_scopes to "Affecting Scopes:",
        R.string.assistant_page_regex_desc to "Define regex patterns to transform messages before sending/receiving",
        R.string.assistant_page_regex_find_regex to "Find Regex",
        R.string.assistant_page_regex_name to "Name",
        R.string.assistant_page_regex_replace_string to "Replace String",
        R.string.assistant_page_regex_title to "Message Regexes",
        R.string.assistant_page_regex_visual_only to "Visual Only (affects display only, not actual message)",
        R.string.assistant_page_remove to "Remove",
        R.string.assistant_page_remove_background to "Remove Background",
        R.string.assistant_page_save to "Save",
        R.string.assistant_page_search_placeholder to "Search assistants",
        R.string.assistant_page_select_background to "Select Background Image",
        R.string.assistant_page_select_from_gallery to "Select from Gallery",
        R.string.assistant_page_stream_output to "Stream Output",
        R.string.assistant_page_stream_output_desc to "Whether to enable streaming output for messages",
        R.string.assistant_page_strict to "Strict",
        R.string.assistant_page_system_prompt to "System Prompt",
        R.string.assistant_page_tab_basic to "Basic Settings",
        R.string.assistant_page_tab_injections to "Prompt Injections",
        R.string.assistant_page_tab_local_tools to "Local Tools",
        R.string.assistant_page_tab_mcp to "MCP",
        R.string.assistant_page_tab_memory to "Memory",
        R.string.assistant_page_tab_prompt to "Prompts",
        R.string.assistant_page_tab_request to "Custom Request",
        R.string.assistant_page_tags to "Tags",
        R.string.assistant_page_temperature to "Temperature",
        R.string.assistant_page_template_preview to "Preview:",
        R.string.assistant_page_template_variable_date to "Date",
        R.string.assistant_page_template_variable_message to "Content",
        R.string.assistant_page_template_variable_role to "Role",
        R.string.assistant_page_template_variable_time to "Time",
        R.string.assistant_page_template_variables_label to "Variables:",
        R.string.assistant_page_thinking_budget to "Thinking Budget",
        R.string.assistant_page_title to "Assistant Settings",
        R.string.assistant_page_top_p to "Top P",
        R.string.assistant_page_top_p_value to "Top P: %s",
        R.string.assistant_page_top_p_warning to "Please don\\'t modify this value unless you know what you\\'re doing",
        R.string.assistant_page_use_assistant_avatar to "Use Assistant Avatar",
        R.string.assistant_page_use_assistant_avatar_desc to "Use assistant avatar and name instead of model avatar and name in chats",
        R.string.audio to "Audio",
        R.string.avatar_cancel to "Cancel",
        R.string.avatar_change_avatar to "Change Avatar",
        R.string.avatar_input_url to "Input URL",
        R.string.avatar_pick_emoji to "Pick Emoji",
        R.string.avatar_pick_image to "Pick Image",
        R.string.avatar_reset to "Reset",
        R.string.avatar_url_confirm to "Confirm",
        R.string.avatar_url_dialog_title to "Input Image URL",
        R.string.avatar_url_hint to "Enter image URL",
        R.string.back to "Back",
        R.string.backup_page_backing_up to "Backing up...",
        R.string.backup_page_backup_items to "Backup Items",
        R.string.backup_page_backup_now to "Backup Now",
        R.string.backup_page_backup_success to "Backup successful",
        R.string.backup_page_chat_records to "Chat Records",
        R.string.backup_page_connection_failed to "Connection failed: %s",
        R.string.backup_page_connection_success to "Connection successful",
        R.string.backup_page_delete to "Delete",
        R.string.backup_page_delete_failed to "Delete failed: %s",
        R.string.backup_page_delete_success to "Delete successful",
        R.string.backup_page_export_desc to "Export app data to a file",
        R.string.backup_page_exporting to "Exporting...",
        R.string.backup_page_files to "Files",
        R.string.backup_page_import_chatbox_desc to "Import data from ChatBox",
        R.string.backup_page_import_desc to "Import local backup file",
        R.string.backup_page_import_export to "Import and Export",
        R.string.backup_page_import_from_chatbox to "Import from ChatBox",
        R.string.backup_page_import_from_other_app to "Import from other app",
        R.string.backup_page_importing to "Importing...",
        R.string.backup_page_loading_failed to "Failed to load backup files: %s",
        R.string.backup_page_local_backup_export to "Export to File",
        R.string.backup_page_local_backup_import to "Import from File",
        R.string.backup_page_password to "Password",
        R.string.backup_page_path to "Path",
        R.string.backup_page_restart_app to "Restart App",
        R.string.backup_page_restart_desc to "The app needs to restart for the changes to take effect.",
        R.string.backup_page_restore to "Restore",
        R.string.backup_page_restore_failed to "Restore failed: %s",
        R.string.backup_page_restore_now to "Restore",
        R.string.backup_page_restore_success to "Restore successful",
        R.string.backup_page_restoring to "Restoring...",
        R.string.backup_page_s3_access_key_id to "Access Key ID",
        R.string.backup_page_s3_backup to "S3 Backup",
        R.string.backup_page_s3_backup_files to "S3 Backup Files",
        R.string.backup_page_s3_bucket to "Bucket",
        R.string.backup_page_s3_endpoint to "Endpoint",
        R.string.backup_page_s3_region to "Region",
        R.string.backup_page_s3_secret_access_key to "Secret Access Key",
        R.string.backup_page_test_connection to "Test Connection",
        R.string.backup_page_title to "Backup and Restore",
        R.string.backup_page_unknown_error to "Unknown error",
        R.string.backup_page_username to "Username",
        R.string.backup_page_webdav_backup to "WebDAV Backup",
        R.string.backup_page_webdav_backup_files to "WebDAV Backup Files",
        R.string.backup_page_webdav_server_address to "WebDAV Server Address",
        R.string.built_in_search_description to "Enable model\\'s built-in search functionality",
        R.string.built_in_search_title to "Built-in Search",
        R.string.calculating to "Calculating...",
        R.string.cancel to "Cancel",
        R.string.cancel_edit to "Cancel Edit",
        R.string.chat_input_placeholder to "Chat with AI",
        R.string.chat_message_tool_call_generic to "Called tool %1\$s",
        R.string.chat_message_tool_call_label to "Called tool %1\$s",
        R.string.chat_message_tool_call_result to "Call result",
        R.string.chat_message_tool_call_title to "Tool Call",
        R.string.chat_message_tool_create_memory to "Created memory",
        R.string.chat_message_tool_delete_memory to "Deleted memory",
        R.string.chat_message_tool_edit_memory to "Updated memory",
        R.string.chat_message_tool_scrape_prefix to "Scrape website: %1\$s",
        R.string.chat_message_tool_scrape_web to "Scrape web page",
        R.string.chat_message_tool_search_prefix to "Search: %1\$s",
        R.string.chat_message_tool_search_results_count to "%1\$d results",
        R.string.chat_message_tool_search_web to "Search web: %1\$s",
        R.string.chat_page_cancel to "Cancel",
        R.string.chat_page_clear_all_errors to "Clear all",
        R.string.chat_page_clear_context to "Clear Context",
        R.string.chat_page_delete to "Delete",
        R.string.chat_page_dismiss_error to "Dismiss error",
        R.string.chat_page_edit_nickname to "Edit Nickname",
        R.string.chat_page_edit_title to "Edit title",
        R.string.chat_page_edit_title_warning to "Please chat first before editing the title",
        R.string.chat_page_export_format to "Export Format",
        R.string.chat_page_export_image to "Export as Image",
        R.string.chat_page_export_image_desc to "Export conversation as PNG image",
        R.string.chat_page_export_image_expand_reasoning to "Expand Reasoning",
        R.string.chat_page_export_markdown to "Markdown",
        R.string.chat_page_export_markdown_desc to "Export conversation as a markdown file",
        R.string.chat_page_export_share_via to "Share via",
        R.string.chat_page_export_success to "Exported to %1\$s",
        R.string.chat_page_history to "Chat History",
        R.string.chat_page_move_to_assistant to "Move to Assistant",
        R.string.chat_page_new_chat to "New Chat",
        R.string.chat_page_new_message to "New message",
        R.string.chat_page_nickname_placeholder to "Please enter nickname",
        R.string.chat_page_no_conversations to "No conversations",
        R.string.chat_page_prompt_injections to "Prompt Injections",
        R.string.chat_page_regenerate_title to "Regenerate title",
        R.string.chat_page_save to "Save",
        R.string.chat_page_scroll_to_bottom to "Scroll to bottom",
        R.string.chat_page_search_placeholder to "Search chats",
        R.string.chat_page_today to "Today",
        R.string.chat_page_yesterday to "Yesterday",
        R.string.chat_size_dialog_content to "Current size: %.2f MB. This may cause the application to crash or lag, or even lose this conversation data. Please create a new conversation as soon as possible to continue chatting.",
        R.string.chat_size_dialog_title to "This conversation data is too large",
        R.string.citations_count to "%1\$d Citations",
        R.string.code_block_collapse to "Collapse",
        R.string.code_block_copy to "Copy Code",
        R.string.code_block_expand to "Expand",
        R.string.code_block_preview to "Preview",
        R.string.collapse_translation to "Collapse Translation",
        R.string.confirm to "Confirm",
        R.string.confirm_delete to "Confirm Delete",
        R.string.copy to "Copy",
        R.string.copy_all to "Copy All",
        R.string.create_fork to "Create a fork",
        R.string.deep_thinking to "Deep Thinking",
        R.string.delete to "Delete",
        R.string.donate_page_afdian_desc to "For 🇨🇳 users",
        R.string.donate_page_donation_methods to "Donation Methods",
        R.string.donate_page_kofi_desc to "For Global Users",
        R.string.donate_page_sponsor_list to "Sponsor List",
        R.string.donate_page_title to "Donate",
        R.string.edit to "Edit",
        R.string.editing to "Editing",
        R.string.emoji_picker_search_placeholder to "Search emojis...",
        R.string.emoji_picker_select_skin_tone to "Select Skin Tone",
        R.string.expand_translation to "Expand Translation",
        R.string.export_cancel to "Cancel",
        R.string.export_image_warning to "\"The above content is generated by artificial intelligence and may contain inaccuracies. \"",
        R.string.export_import_failed to "Import failed: %s",
        R.string.export_import_success to "Imported successfully",
        R.string.export_share to "Share",
        R.string.export_share_desc to "Share via other apps",
        R.string.export_title to "Export",
        R.string.export_to_file to "Export to file",
        R.string.export_to_file_desc to "Save as JSON file",
        R.string.history_page_cancel to "Cancel",
        R.string.history_page_clear to "Clear",
        R.string.history_page_conversation_deleted to "Conversation deleted",
        R.string.history_page_delete to "Delete",
        R.string.history_page_delete_all to "Delete All",
        R.string.history_page_delete_all_confirmation to "Are you sure you want to delete all conversations? This action cannot be undone.",
        R.string.history_page_delete_all_conversations to "Delete All Conversations",
        R.string.history_page_new_conversation to "New Conversation",
        R.string.history_page_pin to "Pin",
        R.string.history_page_search to "Search",
        R.string.history_page_search_placeholder to "Enter keywords to search chat",
        R.string.history_page_title to "Chat History",
        R.string.history_page_undo to "Undo",
        R.string.history_page_unpin to "Unpin",
        R.string.imggen_page_aspect_ratio to "Image Aspect Ratio",
        R.string.imggen_page_aspect_ratio_desc to "Select aspect ratio for generated images",
        R.string.imggen_page_aspect_ratio_landscape to "16:9 Landscape",
        R.string.imggen_page_aspect_ratio_portrait to "9:16 Portrait",
        R.string.imggen_page_aspect_ratio_square to "1:1 Square",
        R.string.imggen_page_cancel to "Cancel",
        R.string.imggen_page_cancel_generation_message to "Are you sure you want to cancel image generation?",
        R.string.imggen_page_cancel_generation_title to "Cancel Generation",
        R.string.imggen_page_confirm to "Confirm",
        R.string.imggen_page_delete to "Delete",
        R.string.imggen_page_gallery to "Gallery",
        R.string.imggen_page_generate_image to "Generate Image",
        R.string.imggen_page_generation_count to "Generation Count",
        R.string.imggen_page_generation_count_desc to "Number of images to generate each time",
        R.string.imggen_page_image_saved_success to "Image saved to gallery",
        R.string.imggen_page_model_selection to "Model Selection",
        R.string.imggen_page_model_selection_desc to "Select AI model for image generation",
        R.string.imggen_page_no_generated_images to "No generated images",
        R.string.imggen_page_prompt_placeholder to "Describe the image you want to generate...",
        R.string.imggen_page_save to "Save",
        R.string.imggen_page_save_failed to "Save failed: %1\$s",
        R.string.imggen_page_settings_title to "Image Generation Settings",
        R.string.imggen_page_title to "Image Generation",
        R.string.injection_selector_empty_hint to "Create mode injections or lorebooks in Settings",
        R.string.injection_selector_empty_title to "No Prompt Injections Available",
        R.string.injection_selector_lorebooks to "Lorebooks",
        R.string.injection_selector_lorebooks_empty to "No lorebooks available",
        R.string.injection_selector_mode_injections to "Mode Injections",
        R.string.injection_selector_mode_injections_empty to "No mode injections available",
        R.string.injection_selector_unnamed to "Unnamed",
        R.string.injection_selector_unnamed_lorebook to "Unnamed Lorebook",
        R.string.language_english to "🇺🇸 English",
        R.string.language_french to "🇫🇷 Français",
        R.string.language_german to "🇩🇪 Deutsch",
        R.string.language_italian to "🇮🇹 Italiano",
        R.string.language_japanese to "🇯🇵 日本語",
        R.string.language_korean to "🇰🇷 한국어",
        R.string.language_simplified_chinese to "🇨🇳 简体中文",
        R.string.language_spanish to "🇪🇸 Español",
        R.string.language_traditional_chinese to "🇨🇳 繁體中文",
        R.string.mcp_picker_syncing to "Syncing MCP servers...",
        R.string.mcp_picker_title to "MCP Servers",
        R.string.menu to "Menu",
        R.string.menu_page_afternoon_greeting to "Good afternoon\\uD83D\\uDC4B",
        R.string.menu_page_ai_translator to "AI Translator",
        R.string.menu_page_evening_greeting to "Good evening\\uD83D\\uDC4B",
        R.string.menu_page_image_generation to "Image Generation",
        R.string.menu_page_knowledge_base to "Knowledge Base (WIP)",
        R.string.menu_page_llm_leaderboard to "LLM Leaderboard",
        R.string.menu_page_morning_greeting to "Good morning\\uD83D\\uDC4B",
        R.string.menu_page_night_greeting to "It\\'s late, take care\\uD83D\\uDC4B",
        R.string.mermaid_export to "Export",
        R.string.mermaid_export_failed to "Export failed",
        R.string.mermaid_export_success to "Export successful",
        R.string.model_list_favorite to "Favorites",
        R.string.model_list_no_providers to "No available AI providers, please add in settings",
        R.string.model_list_search_placeholder to "Enter model name to search",
        R.string.model_list_select_model to "Select Model",
        R.string.more_options to "More options",
        R.string.no_text_content_to_copy to "No text content available to copy",
        R.string.notification_channel_chat_completed to "Chat Completed",
        R.string.notification_chat_done_title to "Chat Message Generated",
        R.string.permission_camera to "Camera",
        R.string.permission_camera_desc to "Camera permission is required to take photos",
        R.string.permission_desc_goto_setting to "Some permissions have been permanently denied, please go to the app settings to manually enable them:",
        R.string.permission_desc_require_permission to "In order to provide a better user experience, the app requires the following permissions:",
        R.string.permission_diaog_title to "Permission Request",
        R.string.permission_go_to_settings to "Go to Setting",
        R.string.permission_notification to "Notification",
        R.string.permission_notification_desc to "Send notifications",
        R.string.permission_permanently_denied to "Permanently Denied",
        R.string.permission_required to "Required",
        R.string.photo to "Photo",
        R.string.pin_chat to "Pin the Chat",
        R.string.pinned_chats to "Pinned Chats",
        R.string.placeholder_battery_level to "Battery Level",
        R.string.placeholder_char to "Assistant Name",
        R.string.placeholder_current_date to "Date",
        R.string.placeholder_current_datetime to "Date and Time",
        R.string.placeholder_current_time to "Time",
        R.string.placeholder_device_info to "Device Info",
        R.string.placeholder_locale to "Locale",
        R.string.placeholder_model_id to "Model ID",
        R.string.placeholder_model_name to "Model Name",
        R.string.placeholder_nickname to "User Nickname",
        R.string.placeholder_system_version to "System Version",
        R.string.placeholder_timezone to "Timezone",
        R.string.placeholder_user to "User",
        R.string.prompt_page_add to "Add",
        R.string.prompt_page_add_entry to "Add Entry",
        R.string.prompt_page_add_lorebook to "Add Lorebook",
        R.string.prompt_page_add_mode_injection to "Add Mode Injection",
        R.string.prompt_page_cancel to "Cancel",
        R.string.prompt_page_case_sensitive to "Case Sensitive",
        R.string.prompt_page_confirm to "Confirm",
        R.string.prompt_page_constant_active to "Always Active",
        R.string.prompt_page_constant_active_desc to "Trigger without keyword matching",
        R.string.prompt_page_delete to "Delete",
        R.string.prompt_page_description to "Description",
        R.string.prompt_page_disabled to "Disabled",
        R.string.prompt_page_edit to "Edit",
        R.string.prompt_page_edit_entry to "Edit Entry",
        R.string.prompt_page_edit_lorebook to "Edit Lorebook",
        R.string.prompt_page_edit_mode_injection to "Edit Mode Injection",
        R.string.prompt_page_empty_hint to "Click the button below to add",
        R.string.prompt_page_enabled to "Enabled",
        R.string.prompt_page_entries_count_format to "%d entries",
        R.string.prompt_page_entries_format to "Entries (%d)",
        R.string.prompt_page_inject_depth to "Inject Depth",
        R.string.prompt_page_injection_content to "Injection Content",
        R.string.prompt_page_injection_position to "Injection Position",
        R.string.prompt_page_keywords_format to "Keywords: %s",
        R.string.prompt_page_keywords_label to "Keywords",
        R.string.prompt_page_lorebook_empty to "No Lorebooks",
        R.string.prompt_page_lorebook_tab to "Lorebook",
        R.string.prompt_page_mode_injection_empty to "No mode injections",
        R.string.prompt_page_mode_injection_tab to "Mode Injection",
        R.string.prompt_page_name to "Name",
        R.string.prompt_page_new_keyword to "New Keyword",
        R.string.prompt_page_position_after_system to "After System Prompt",
        R.string.prompt_page_position_at_depth to "At Depth",
        R.string.prompt_page_position_before_system to "Before System Prompt",
        R.string.prompt_page_position_bottom_of_chat to "Before Latest Message",
        R.string.prompt_page_position_top_of_chat to "Top of Chat",
        R.string.prompt_page_priority_format to "Priority: %d",
        R.string.prompt_page_priority_label to "Priority",
        R.string.prompt_page_scan_depth to "Scan Depth (Messages)",
        R.string.prompt_page_title to "Prompt Injection",
        R.string.prompt_page_unnamed to "Unnamed",
        R.string.prompt_page_unnamed_entry to "Unnamed Entry",
        R.string.prompt_page_unnamed_lorebook to "Unnamed Lorebook",
        R.string.prompt_page_use_regex to "Use Regular Expression",
        R.string.reasoning_auto to "Auto",
        R.string.reasoning_auto_desc to "Let the model automatically determine reasoning level.",
        R.string.reasoning_custom to "Custom reasoning budget",
        R.string.reasoning_heavy to "Heavy reasoning",
        R.string.reasoning_heavy_desc to "The model will use a large amount of reasoning to answer questions.",
        R.string.reasoning_light to "Light reasoning",
        R.string.reasoning_light_desc to "The model will use a small amount of reasoning to answer questions.",
        R.string.reasoning_medium to "Medium reasoning",
        R.string.reasoning_medium_desc to "The model will use more reasoning to answer questions.",
        R.string.reasoning_off to "Off",
        R.string.reasoning_off_desc to "Turn off reasoning functionality, the model will directly answer questions.",
        R.string.regenerate to "Regenerate",
        R.string.render_with_webview to "Render with WebView",
        R.string.search_ability_scrape to "Scrape",
        R.string.search_ability_search to "Search",
        R.string.search_picker_title to "Search Settings",
        R.string.select_and_copy to "Select and Copy",
        R.string.send to "Send",
        R.string.setting_display_page_amoled_dark_mode_desc to "Use pure black background in dark theme, suitable for AMOLED screens",
        R.string.setting_display_page_amoled_dark_mode_title to "AMOLED Dark Mode",
        R.string.setting_display_page_auto_collapse_thinking_desc to "Automatically collapse thinking content after thinking is complete",
        R.string.setting_display_page_auto_collapse_thinking_title to "Auto Collapse Thinking",
        R.string.setting_display_page_chat_list_model_icon_desc to "Whether to display model icons in chat list messages",
        R.string.setting_display_page_chat_list_model_icon_title to "Chat List Model Icon",
        R.string.setting_display_page_code_block_auto_collapse_desc to "Automatically collapse code blocks by default",
        R.string.setting_display_page_code_block_auto_collapse_title to "Code Block Auto Collapse",
        R.string.setting_display_page_code_block_auto_wrap_desc to "Automatically wrap long lines in code blocks",
        R.string.setting_display_page_code_block_auto_wrap_title to "Code Block Auto Wrap",
        R.string.setting_display_page_create_new_conversation_on_start_desc to "Create a new conversation when the app starts",
        R.string.setting_display_page_create_new_conversation_on_start_title to "New chat on launch",
        R.string.setting_display_page_developer_mode to "Developer Mode",
        R.string.setting_display_page_developer_mode_desc to "Show more debugging features. Not recommended for general users.",
        R.string.setting_display_page_enable_message_generation_haptic_effect_desc to "Enable haptic feedback when messages are being generated",
        R.string.setting_display_page_enable_message_generation_haptic_effect_title to "Message Generation Haptic Effect",
        R.string.setting_display_page_font_size_preview to "This is a **sample** chat text",
        R.string.setting_display_page_font_size_title to "Chat Font Size",
        R.string.setting_display_page_message_jumper_position_desc to "Move  Message Jumper to left side",
        R.string.setting_display_page_message_jumper_position_title to "Message Jumper Position",
        R.string.setting_display_page_notification_message_generated to "Enable notification after message generated",
        R.string.setting_display_page_notification_message_generated_desc to "Show a notification when a message is generated if the app is not in the foreground",
        R.string.setting_display_page_show_line_numbers_desc to "Display line numbers in code blocks",
        R.string.setting_display_page_show_line_numbers_title to "Show Line Numbers",
        R.string.setting_display_page_show_message_jumper_desc to "Display quick jump buttons on the right when scrolling the chat list",
        R.string.setting_display_page_show_message_jumper_title to "Show Message Jumper",
        R.string.setting_display_page_show_model_name_desc to "Whether to display model names in chat messages",
        R.string.setting_display_page_show_model_name_title to "Show Model Name",
        R.string.setting_display_page_show_token_usage_desc to "Display token usage and message count",
        R.string.setting_display_page_show_token_usage_title to "Show Token & Context Stats",
        R.string.setting_display_page_show_updates_desc to "Whether to display app update notifications",
        R.string.setting_display_page_show_updates_title to "Show Updates",
        R.string.setting_display_page_show_user_avatar_desc to "Whether to display user avatar in chat messages",
        R.string.setting_display_page_show_user_avatar_title to "Show User Avatar",
        R.string.setting_display_page_skip_crop_image_desc to "Skip crop interface after importing images or taking photos",
        R.string.setting_display_page_skip_crop_image_title to "Skip Image Editing",
        R.string.setting_display_page_title to "Display Settings",
        R.string.setting_mcp_page_add_header to "Add Header",
        R.string.setting_mcp_page_add_one_to_get_started to "Add one to get started",
        R.string.setting_mcp_page_basic_settings to "Basic Settings",
        R.string.setting_mcp_page_custom_headers to "Custom Headers",
        R.string.setting_mcp_page_custom_headers_desc to "Add custom HTTP headers for MCP server requests",
        R.string.setting_mcp_page_delete_header to "Delete Header",
        R.string.setting_mcp_page_enable to "Enable",
        R.string.setting_mcp_page_enable_desc to "Whether to enable this MCP server",
        R.string.setting_mcp_page_header_name to "Header Name",
        R.string.setting_mcp_page_header_name_placeholder to "e.g.: Authorization",
        R.string.setting_mcp_page_header_value to "Header Value",
        R.string.setting_mcp_page_header_value_placeholder to "e.g.: Bearer token123",
        R.string.setting_mcp_page_name to "Name",
        R.string.setting_mcp_page_name_desc to "Display name for the MCP server",
        R.string.setting_mcp_page_name_placeholder to "e.g.: My MCP Server",
        R.string.setting_mcp_page_no_mcp_servers_found to "No MCP servers found",
        R.string.setting_mcp_page_save to "Save",
        R.string.setting_mcp_page_server_url to "Server URL",
        R.string.setting_mcp_page_sse_url_desc to "URL address for SSE transport server",
        R.string.setting_mcp_page_sse_url_placeholder to "https://example.com/sse",
        R.string.setting_mcp_page_streamable_http_url_desc to "URL address for Streamable HTTP server",
        R.string.setting_mcp_page_streamable_http_url_placeholder to "https://example.com/mcp",
        R.string.setting_mcp_page_title to "MCP",
        R.string.setting_mcp_page_tools to "Tools",
        R.string.setting_mcp_page_tools_unavailable_message to "Cannot view tool list when adding MCP Server, please check back after adding",
        R.string.setting_mcp_page_transport_type to "Transport Type",
        R.string.setting_mcp_page_transport_type_desc to "Select the transport protocol type for the MCP server",
        R.string.setting_mcp_page_url_label to "URL",
        R.string.setting_model_page_chat_model to "Chat Model",
        R.string.setting_model_page_chat_model_desc to "Global default chat model",
        R.string.setting_model_page_ocr_model to "OCR Model",
        R.string.setting_model_page_ocr_model_desc to "Model used for optical character recognition on images",
        R.string.setting_model_page_ocr_prompt_vars to "Variables: Image data: {images}",
        R.string.setting_model_page_prompt to "Prompt",
        R.string.setting_model_page_reset_to_default to "Reset to default",
        R.string.setting_model_page_suggestion_model to "Chat Suggestion Model",
        R.string.setting_model_page_suggestion_model_desc to "Model used to generate conversation suggestions, recommend using fast and inexpensive models",
        R.string.setting_model_page_suggestion_prompt_vars to "Variables: Conversation content: {content}, Language: {locale}",
        R.string.setting_model_page_title to "Model Settings",
        R.string.setting_model_page_title_model to "Title Summary Model",
        R.string.setting_model_page_title_model_desc to "Model used to summarize conversation titles, recommend using fast and inexpensive models",
        R.string.setting_model_page_translate_model to "Translation Model",
        R.string.setting_model_page_translate_model_desc to "The model used for translation features",
        R.string.setting_model_page_translate_prompt_vars to "Variables: Source text: {source_text}, Target language: {target_lang}",
        R.string.setting_page_about to "About",
        R.string.setting_page_about_desc to "About this app",
        R.string.setting_page_assistant to "Assistant",
        R.string.setting_page_assistant_desc to "Set up personalized assistants (agents)",
        R.string.setting_page_basic_settings to "Basic Settings",
        R.string.setting_page_built_in_tools to "Built-in Tools",
        R.string.setting_page_built_in_tools_desc to "Select built-in tools supported by the model. These tools are directly provided by the API without requiring app support. Currently, this feature is only supported by the official Gemini API.",
        R.string.setting_page_built_in_tools_search to "Search",
        R.string.setting_page_built_in_tools_search_desc to "Enable Google Search integration",
        R.string.setting_page_built_in_tools_url_context to "URL Context",
        R.string.setting_page_built_in_tools_url_context_desc to "Enable URL content processing",
        R.string.setting_page_chat_settings to "Chat Settings",
        R.string.setting_page_chat_storage to "Chat Storage",
        R.string.setting_page_chat_storage_desc to "%1\$d files, %2\$.2f MB",
        R.string.setting_page_color_mode to "Color Mode",
        R.string.setting_page_color_mode_dark to "Dark",
        R.string.setting_page_color_mode_light to "Light",
        R.string.setting_page_color_mode_system to "System",
        R.string.setting_page_config to "Configure",
        R.string.setting_page_config_api_desc to "You haven\\'t configured API and model yet, please configure first",
        R.string.setting_page_config_api_title to "Please configure API and model",
        R.string.setting_page_data_backup to "Data Backup",
        R.string.setting_page_data_backup_desc to "Backup and restore app data",
        R.string.setting_page_data_settings to "Data Settings",
        R.string.setting_page_default_model to "Default Model and Prompt",
        R.string.setting_page_default_model_desc to "Set default models for each feature",
        R.string.setting_page_display_setting to "Display Settings",
        R.string.setting_page_display_setting_desc to "Manage display settings",
        R.string.setting_page_documentation to "Documentation",
        R.string.setting_page_documentation_desc to "View app usage instructions and help documentation",
        R.string.setting_page_donate to "Donate",
        R.string.setting_page_donate_desc to "If you like it, sponsor the author\\'s work",
        R.string.setting_page_dynamic_color to "Dynamic Color",
        R.string.setting_page_dynamic_color_desc to "Use dynamic color",
        R.string.setting_page_general_settings to "General Settings",
        R.string.setting_page_mcp to "MCP",
        R.string.setting_page_mcp_desc to "Configure MCP Servers",
        R.string.setting_page_model_and_services to "Models & Services",
        R.string.setting_page_no_share_app to "No sharing app found",
        R.string.setting_page_prompts_desc to "Configure mode or regex-based prompt injections",
        R.string.setting_page_prompts_title to "Prompt Injections",
        R.string.setting_page_providers to "Providers",
        R.string.setting_page_providers_desc to "Configure AI providers",
        R.string.setting_page_request_logs to "Request Logs",
        R.string.setting_page_request_logs_desc to "View HTTP request logs",
        R.string.setting_page_search_add_provider to "Add Provider",
        R.string.setting_page_search_common_options to "Common Options",
        R.string.setting_page_search_delete_provider to "Delete Provider",
        R.string.setting_page_search_providers to "Search Providers",
        R.string.setting_page_search_result_size to "Result Size",
        R.string.setting_page_search_service to "Search Service",
        R.string.setting_page_search_service_desc to "Set up search service",
        R.string.setting_page_search_title to "Search Service",
        R.string.setting_page_share to "Share",
        R.string.setting_page_share_desc to "Share this app with friends",
        R.string.setting_page_share_text to "RikkaHub - Open Source Android AI Assistant\\n\\nWebsite: https://rikka-ai.com/",
        R.string.setting_page_theme_setting to "Theme Settings",
        R.string.setting_page_tts_service to "Text-to-Speech Service",
        R.string.setting_page_tts_service_desc to "Configure text-to-speech service providers",
        R.string.setting_provider_page_abilities to "Abilities",
        R.string.setting_provider_page_add to "Add",
        R.string.setting_provider_page_add_model to "Add Model",
        R.string.setting_provider_page_add_models_hint to "Click the button below to add models",
        R.string.setting_provider_page_add_new_model to "Add New Model",
        R.string.setting_provider_page_add_provider to "Add Provider",
        R.string.setting_provider_page_add_provider_override to "Add Provider Override",
        R.string.setting_provider_page_advanced_settings to "Advanced Settings",
        R.string.setting_provider_page_api_base_url to "API Base Url",
        R.string.setting_provider_page_api_key to "API Key",
        R.string.setting_provider_page_api_path to "API Path",
        R.string.setting_provider_page_avaliable_models to "Avaliable Models",
        R.string.setting_provider_page_balance_api_path to "Balance API Path",
        R.string.setting_provider_page_balance_info to "\"Get account balance \"",
        R.string.setting_provider_page_balance_json_key to "Result Json Key",
        R.string.setting_provider_page_basic_settings to "Basic Settings",
        R.string.setting_provider_page_chat_model to "Chat",
        R.string.setting_provider_page_configuration to "Configuration",
        R.string.setting_provider_page_configure_provider_override to "Configure Provider Override",
        R.string.setting_provider_page_delete_dialog_text to "Are you sure you want to delete this provider? This action cannot be undone.",
        R.string.setting_provider_page_deselect_models to "Deselect All",
        R.string.setting_provider_page_disabled to "Disabled",
        R.string.setting_provider_page_edit_model to "Edit Model",
        R.string.setting_provider_page_embedding_model to "Embedding",
        R.string.setting_provider_page_enable to "Enable",
        R.string.setting_provider_page_enabled to "Enabled",
        R.string.setting_provider_page_filter_example to "e.g.: GPT-3.5",
        R.string.setting_provider_page_filter_placeholder to "Enter model name to filter",
        R.string.setting_provider_page_image to "Image",
        R.string.setting_provider_page_image_model to "Image",
        R.string.setting_provider_page_image_qr_decode_failed to "Failed to parse QR code from image: %s",
        R.string.setting_provider_page_import_dialog_message to "Please select import method:",
        R.string.setting_provider_page_import_dialog_title to "Import Provider Configuration",
        R.string.setting_provider_page_import_success to "Import successful",
        R.string.setting_provider_page_input_modality to "Input Modality",
        R.string.setting_provider_page_location to "Location (e.g. us-central1)",
        R.string.setting_provider_page_model_count to "%d models",
        R.string.setting_provider_page_model_display_name to "Model Display Name",
        R.string.setting_provider_page_model_display_name_placeholder to "e.g.: GPT-3.5, for UI display",
        R.string.setting_provider_page_model_id to "Model ID",
        R.string.setting_provider_page_model_id_placeholder to "e.g.: gpt-3.5-turbo",
        R.string.setting_provider_page_model_name to "Model Name",
        R.string.setting_provider_page_model_type to "Model Type",
        R.string.setting_provider_page_models to "Models",
        R.string.setting_provider_page_name to "Name",
        R.string.setting_provider_page_network_proxy to "Network Proxy",
        R.string.setting_provider_page_no_models to "No models",
        R.string.setting_provider_page_no_permission to "No permission",
        R.string.setting_provider_page_no_qr_found to "No valid QR code found",
        R.string.setting_provider_page_output_modality to "Output Modality",
        R.string.setting_provider_page_private_key to "Private Key",
        R.string.setting_provider_page_project_id to "Project Id",
        R.string.setting_provider_page_provider_override to "Provider Override",
        R.string.setting_provider_page_provider_override_desc to "Configure custom provider settings for this specific model. Will inherit common properties from parent provider.",
        R.string.setting_provider_page_proxy_host to "Host",
        R.string.setting_provider_page_proxy_password to "Password (Optional)",
        R.string.setting_provider_page_proxy_port to "Port",
        R.string.setting_provider_page_proxy_username to "Username (Optional)",
        R.string.setting_provider_page_qr_decode_failed to "Failed to parse QR code: %s",
        R.string.setting_provider_page_reasoning to "Reasoning",
        R.string.setting_provider_page_response_api to "Response API",
        R.string.setting_provider_page_response_api_warning to "Response API is OpenAI\\'s next-generation API. Most providers do not support it. If you don\\'t know what this is, don\\'t enable it.",
        R.string.setting_provider_page_save to "Save",
        R.string.setting_provider_page_save_success to "Save successful",
        R.string.setting_provider_page_scan_error to "Error: %s",
        R.string.setting_provider_page_scan_qr_code to "Scan QR Code",
        R.string.setting_provider_page_search_providers to "Search providers",
        R.string.setting_provider_page_select_all to "Select All (%1\$d)",
        R.string.setting_provider_page_select_from_gallery to "Select from Gallery",
        R.string.setting_provider_page_service_account_email to "Service Account Email",
        R.string.setting_provider_page_test to "Test",
        R.string.setting_provider_page_test_connection to "Test Connection",
        R.string.setting_provider_page_test_success to "Test Successful",
        R.string.setting_provider_page_text to "Text",
        R.string.setting_provider_page_title to "Providers",
        R.string.setting_provider_page_tool to "Tool",
        R.string.setting_provider_page_vertex_ai to "Vertex AI",
        R.string.setting_tts_page_add to "Add",
        R.string.setting_tts_page_add_provider to "Add TTS Provider",
        R.string.setting_tts_page_add_provider_content_description to "Add TTS Provider",
        R.string.setting_tts_page_api_key to "API Key",
        R.string.setting_tts_page_api_key_description to "Your provider API key",
        R.string.setting_tts_page_api_key_placeholder_gemini to "AIza...",
        R.string.setting_tts_page_api_key_placeholder_openai to "sk-...",
        R.string.setting_tts_page_base_url to "Base URL",
        R.string.setting_tts_page_base_url_description to "API base URL endpoint",
        R.string.setting_tts_page_base_url_placeholder to "https://api.openai.com/v1",
        R.string.setting_tts_page_default_name to "System TTS",
        R.string.setting_tts_page_edit_provider to "Edit Provider",
        R.string.setting_tts_page_emotion to "Emotion",
        R.string.setting_tts_page_emotion_description to "Emotion style for speech synthesis",
        R.string.setting_tts_page_model to "Model",
        R.string.setting_tts_page_model_description to "TTS model to use",
        R.string.setting_tts_page_model_placeholder_gemini to "gemini-2.5-flash-preview-tts",
        R.string.setting_tts_page_model_placeholder_openai to "gpt-4o-mini-tts",
        R.string.setting_tts_page_more_options_content_description to "More options",
        R.string.setting_tts_page_name to "Name",
        R.string.setting_tts_page_name_description to "Custom name for this TTS provider",
        R.string.setting_tts_page_name_placeholder to "Enter provider name",
        R.string.setting_tts_page_pitch to "Pitch",
        R.string.setting_tts_page_pitch_description to "Control the pitch of speech (0.1 - 2.0, 1.0 is normal)",
        R.string.setting_tts_page_provider_gemini to "Gemini",
        R.string.setting_tts_page_provider_openai to "OpenAI",
        R.string.setting_tts_page_provider_system to "System TTS",
        R.string.setting_tts_page_provider_type to "Provider Type",
        R.string.setting_tts_page_provider_type_description to "Select the TTS provider type",
        R.string.setting_tts_page_selected to "Selected",
        R.string.setting_tts_page_speech_rate to "Speech Rate",
        R.string.setting_tts_page_speech_rate_description to "Control the speed of speech (0.1 - 3.0, 1.0 is normal)",
        R.string.setting_tts_page_speed to "Speed",
        R.string.setting_tts_page_speed_description to "Speech speed (0.25 - 4.0)",
        R.string.setting_tts_page_test_text to "Hello, this is a text-to-speech test.",
        R.string.setting_tts_page_title to "Text-to-Speech",
        R.string.setting_tts_page_voice to "Voice",
        R.string.setting_tts_page_voice_description to "Voice to use for speech synthesis",
        R.string.setting_tts_page_voice_id to "Voice ID",
        R.string.setting_tts_page_voice_id_description to "Voice ID for speech synthesis",
        R.string.setting_tts_page_voice_name to "Voice Name",
        R.string.setting_tts_page_voice_name_description to "Name of the voice",
        R.string.setting_tts_page_voice_name_placeholder to "Kore",
        R.string.settings to "Settings",
        R.string.share to "Share",
        R.string.share_handler_page_title to "Select an Assistant",
        R.string.shortcut_take_picture to "Take Picture & Ask",
        R.string.silicon_flow_built_in_models to "* Built-in Silicon Flow free models are available without an API Key. For more powerful models, please apply and configure your own API Key.",
        R.string.silicon_flow_description to "**Leading global AI capability provider, accelerating AGI to benefit humanity.**",
        R.string.silicon_flow_website to "Website: [https://cloud.siliconflow.cn/](https://cloud.siliconflow.cn/i/u1Ia4Ycf)",
        R.string.stop to "Stop",
        R.string.tag_input_dialog_create_new to "Create New Tag",
        R.string.tag_input_dialog_existing_tags to "Existing Tags",
        R.string.tag_input_dialog_label to "Tag Name",
        R.string.tag_input_dialog_placeholder to "Enter tag name...",
        R.string.tag_input_dialog_tag_exists to "Tag with this name already exists",
        R.string.tag_input_dialog_title to "Add Tag",
        R.string.take_picture to "Take Picture",
        R.string.test_tts to "Test TTS",
        R.string.text_area_fullscreen_edit to "Fullscreen edit",
        R.string.text_area_import_failed to "Failed to import file",
        R.string.text_area_import_from_file to "Import from file",
        R.string.text_area_import_success to "File imported successfully",
        R.string.text_area_save to "Save",
        R.string.theme_name_autumn to "Autumn Yellow",
        R.string.theme_name_black to "Neutral Black",
        R.string.theme_name_ocean to "Ocean Blue",
        R.string.theme_name_sakura to "Sakura Pink",
        R.string.theme_name_spring to "Meadow Green",
        R.string.tools_warning to "The current model does not have tool calling enabled. Please enable the model\\'s tool capabilities in the settings to use features like search/MCP.",
        R.string.translate to "Translate",
        R.string.translating to "Translating...",
        R.string.translation_clear to "Clear Translation",
        R.string.translation_language_selection_title to "Select Translation Language",
        R.string.translation_text to "Translation",
        R.string.translator_page_cancel to "Cancel",
        R.string.translator_page_input_placeholder to "Enter text to translate...",
        R.string.translator_page_result_placeholder to "Translation result will be shown here",
        R.string.translator_page_title to "Translator",
        R.string.translator_page_translate to "Translate",
        R.string.tts to "TTS",
        R.string.unpin_chat to "Unpin the Chat",
        R.string.upload_file to "Upload File",
        R.string.use_web_search to "Web Search",
        R.string.user_default_name to "User",
        R.string.video to "Video",
        R.string.web_search_disabled to "Web search disabled",
        R.string.web_search_enabled to "Web search enabled",
    )
}
